
import type {Metadata} from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'BabelPhish',
  description: 'Generated by Firebase Studio',
  icons: {
    icon: '/bablephish_logo.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
      </head>
      <body className="font-body antialiased">
        {children}
      </body>
    </html>
  );
}
